@echo off
echo Installing dependencies (if needed)...
.\.venv\Scripts\python.exe -m pip install -r requirements.txt
echo Starting server with venv Python...
.\.venv\Scripts\python.exe -m uvicorn main:app --reload
